### ISSUE TITLE
Voorkom dezelfde naam

### ISSUE THREAD

**Issue by Coenmathijssen** [ManoukK/real-time-web-1920#18]
Ik zou misschien nog een fallback maken om te voorkomen dat iemand twee keer zijn naam kan invoeren. Dit kan je doen door bij te houden welke namen zijn ingevoerd en connected zijn. Vervolgens kan je een error geven bij dezelfde naam of er een reeks tekens achteraan te plakken.

**Comment by ManoukK** [comment]
yes heb ik gedaan. Er word nu gecheckt of de naam al in de array staat en zo ja dan word er een nummer achter gezet van hoelang de array is zodat het elke keer een ander nummer is en dat je het met math random ook niet toevallig 2 dezelfde nummers kan hebben
