### ISSUE TITLE
Data Life Cycle opslaan van data

### ISSUE THREAD

**Issue by Coenmathijssen** [ManoukK/real-time-web-1920#25]
Wat mij logischer lijkt, is dat je de data opvraagt van de API. Vervolgens die data op de server gaat cleanen en dat daarna geheel opslaat in je database. Als de spelers dan een spel beginnen, kan je eerst checken of het nog op de server leeft (snelste manier), daarna of het in je database leeft en als beide niet het geval is het weer ophalen vanuit je API. Ik weet niet of het handig is om eerst te kijken of je server het nog heeft, maar dat moet je zelf even checken.

**Comment by ManoukK** [comment]
Uiteindelijk leeft alle data in mijn server en wil ik pas data naar de database sturen als de game is afgelopen.
