### ISSUE TITLE
Kijk nog even goed welke gebruiker welke data krijgt in je Data Life Cycle

### ISSUE THREAD

**Issue by Coenmathijssen** [ManoukK/real-time-web-1920#26]
De tekenaar krijgt andere data dan de andere gebruikers. De tekenaar krijgt de meta data van de film, de rest niet. De overige gebruikers krijgen wel de tekening data van de tekenaar (via socket) en staan met elkaar in verbinding via de chat. Deze data uitwisseling klopt nog niet helemaal in het model.

**Comment by ManoukK** [comment]
Ik heb nu twee verschillende users toegevoegd de tekenaar en de rader. Hierdoor is de DLC een stuk overzichtelijker
